// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Requra.Infrastructure.Data;

#nullable disable

namespace Requra.Infrastructure.Migrations
{
    [DbContext(typeof(RequraDbContext))]
    [Migration("20260812121339_MakeProjectReviewStakeholderIdNullable")]
    partial class MakeProjectReviewStakeholderIdNullable
    {
    }
}
